import { Component } from '@angular/core';

@Component({
  selector: 'countries',
  imports: [],
  templateUrl: './countries.html',
  styleUrl: './countries.scss',
})
export class Countries {
  countryCommonNames: any[] = [
    {
      country: 'United States',
      commonMenName: 'John',
      commonWomenName: 'Mary',
      propertyUrl: 'https://flagcdn.com/w1280/us.png',
    },
    {
      country: 'Canada',
      commonMenName: 'John',
      commonWomenName: 'Mary',
      propertyUrl: 'https://flagcdn.com/w1280/ca.png',
    },
    {
      country: 'Mexico',
      commonMenName: 'Jose',
      commonWomenName: 'Maria',
      propertyUrl: 'https://flagcdn.com/w1280/mx.png',
    },
    {
      country: 'Argentina',
      commonMenName: 'Juan',
      commonWomenName: 'Maria',
      propertyUrl: 'https://flagcdn.com/w1280/ar.png',
    },
    {
      country: 'Brazil',
      commonMenName: 'Jose',
      commonWomenName: 'Maria',
      propertyUrl: 'https://flagcdn.com/w1280/br.png',
    },
    {
      country: 'Colombia',
      commonMenName: 'Luis',
      commonWomenName: 'Ana',
      propertyUrl: 'https://flagcdn.com/w1280/co.png',
    },
    {
      country: 'Chile',
      commonMenName: 'Juan',
      commonWomenName: 'Maria',
      propertyUrl: 'https://flagcdn.com/w1280/cl.png',
    },
    {
      country: 'Peru',
      commonMenName: 'Jose',
      commonWomenName: 'Maria',
      propertyUrl: 'https://flagcdn.com/w1280/pe.png',
    },
    {
      country: 'England',
      commonMenName: 'John',
      commonWomenName: 'Mary',
      propertyUrl: 'https://flagcdn.com/w1280/gb-eng.png',
    },
    {
      country: 'Scotland',
      commonMenName: 'James',
      commonWomenName: 'Isla',
      propertyUrl: 'https://flagcdn.com/w1280/gb-sct.png',
    },
    {
      country: 'Wales',
      commonMenName: 'Dylan',
      commonWomenName: 'Megan',
      propertyUrl: 'https://flagcdn.com/w1280/gb-wls.png',
    },
    {
      country: 'Ireland',
      commonMenName: 'Patrick',
      commonWomenName: 'Mary',
      propertyUrl: 'https://flagcdn.com/w1280/ie.png',
    },
    {
      country: 'Spain',
      commonMenName: 'Jose',
      commonWomenName: 'Maria',
      propertyUrl: 'https://flagcdn.com/w1280/es.png',
    },
    {
      country: 'Portugal',
      commonMenName: 'Joao',
      commonWomenName: 'Ana',
      propertyUrl: 'https://flagcdn.com/w1280/pt.png',
    },
    {
      country: 'France',
      commonMenName: 'Jean',
      commonWomenName: 'Marie',
      propertyUrl: 'https://flagcdn.com/w1280/fr.png',
    },
    {
      country: 'Germany',
      commonMenName: 'Michael',
      commonWomenName: 'Anna',
      propertyUrl: 'https://flagcdn.com/w1280/de.png',
    },
    {
      country: 'Netherlands',
      commonMenName: 'Jan',
      commonWomenName: 'Maria',
      propertyUrl: 'https://flagcdn.com/w1280/nl.png',
    },
    {
      country: 'Italy',
      commonMenName: 'Francesco',
      commonWomenName: 'Giulia',
      propertyUrl: 'https://flagcdn.com/w1280/it.png',
    },
    {
      country: 'Sweden',
      commonMenName: 'Erik',
      commonWomenName: 'Anna',
      propertyUrl: 'https://flagcdn.com/w1280/se.png',
    },
    {
      country: 'Norway',
      commonMenName: 'Ole',
      commonWomenName: 'Anne',
      propertyUrl: 'https://flagcdn.com/w1280/no.png',
    },
    {
      country: 'Denmark',
      commonMenName: 'Lars',
      commonWomenName: 'Anne',
      propertyUrl: 'https://flagcdn.com/w1280/dk.png',
    },
    {
      country: 'Poland',
      commonMenName: 'Michal',
      commonWomenName: 'Agnieszka',
      propertyUrl: 'https://flagcdn.com/w1280/pl.png',
    },
    {
      country: 'Romania',
      commonMenName: 'Andrei',
      commonWomenName: 'Elena',
      propertyUrl: 'https://flagcdn.com/w1280/ro.png',
    },
    {
      country: 'Greece',
      commonMenName: 'Georgios',
      commonWomenName: 'Maria',
      propertyUrl: 'https://flagcdn.com/w1280/gr.png',
    },
    {
      country: 'Turkey',
      commonMenName: 'Mehmet',
      commonWomenName: 'Fatma',
      propertyUrl: 'https://flagcdn.com/w1280/tr.png',
    },
    {
      country: 'Russia',
      commonMenName: 'Sergey',
      commonWomenName: 'Elena',
      propertyUrl: 'https://flagcdn.com/w1280/ru.png',
    },
    {
      country: 'Ukraine',
      commonMenName: 'Bohdan',
      commonWomenName: 'Sofyia',
      propertyUrl: 'https://flagcdn.com/w1280/ua.png',
    },
    {
      country: 'Hungary',
      commonMenName: 'Laszlo',
      commonWomenName: 'Eva',
      propertyUrl: 'https://flagcdn.com/w1280/hu.png',
    },
    {
      country: 'Czech Republic',
      commonMenName: 'Jan',
      commonWomenName: 'Jana',
      propertyUrl: 'https://flagcdn.com/w1280/cz.png',
    },
    {
      country: 'Austria',
      commonMenName: 'Franz',
      commonWomenName: 'Elisabeth',
      propertyUrl: 'https://flagcdn.com/w1280/at.png',
    },
    {
      country: 'Switzerland',
      commonMenName: 'Peter',
      commonWomenName: 'Ruth',
      propertyUrl: 'https://flagcdn.com/w1280/ch.png',
    },
    {
      country: 'Belgium',
      commonMenName: 'Marc',
      commonWomenName: 'Marie',
      propertyUrl: 'https://flagcdn.com/w1280/be.png',
    },
    {
      country: 'Serbia',
      commonMenName: 'Nikola',
      commonWomenName: 'Milica',
      propertyUrl: 'https://flagcdn.com/w1280/rs.png',
    },
    {
      country: 'Croatia',
      commonMenName: 'Ivan',
      commonWomenName: 'Ana',
      propertyUrl: 'https://flagcdn.com/w1280/hr.png',
    },
    {
      country: 'Bulgaria',
      commonMenName: 'Georgi',
      commonWomenName: 'Mariya',
      propertyUrl: 'https://flagcdn.com/w1280/bg.png',
    },
    {
      country: 'Japan',
      commonMenName: 'Hiroshi',
      commonWomenName: 'Yoko',
      propertyUrl: 'https://flagcdn.com/w1280/jp.png',
    },
    {
      country: 'China',
      commonMenName: 'Wei',
      commonWomenName: 'Mei',
      propertyUrl: 'https://flagcdn.com/w1280/cn.png',
    },
    {
      country: 'India',
      commonMenName: 'Rahul',
      commonWomenName: 'Priya',
      propertyUrl: 'https://flagcdn.com/w1280/in.png',
    },
    {
      country: 'Indonesia',
      commonMenName: 'Agus',
      commonWomenName: 'Sri',
      propertyUrl: 'https://flagcdn.com/w1280/id.png',
    },
    {
      country: 'Philippines',
      commonMenName: 'John',
      commonWomenName: 'Maria',
      propertyUrl: 'https://flagcdn.com/w1280/ph.png',
    },
    {
      country: 'Vietnam',
      commonMenName: 'Hung',
      commonWomenName: 'Trang',
      propertyUrl: 'https://flagcdn.com/w1280/vn.png',
    },
    {
      country: 'Thailand',
      commonMenName: 'Somchai',
      commonWomenName: 'Siriporn',
      propertyUrl: 'https://flagcdn.com/w1280/th.png',
    },
    {
      country: 'Malaysia',
      commonMenName: 'Mohamed',
      commonWomenName: 'Siti',
      propertyUrl: 'https://flagcdn.com/w1280/my.png',
    },
    {
      country: 'Saudi Arabia',
      commonMenName: 'Abdullah',
      commonWomenName: 'Fatimah',
      propertyUrl: 'https://flagcdn.com/w1280/sa.png',
    },
    {
      country: 'Iran',
      commonMenName: 'Mohammad',
      commonWomenName: 'Zahra',
      propertyUrl: 'https://flagcdn.com/w1280/ir.png',
    },
    {
      country: 'Pakistan',
      commonMenName: 'Muhammad',
      commonWomenName: 'Ayesha',
      propertyUrl: 'https://flagcdn.com/w1280/pk.png',
    },
    {
      country: 'Israel',
      commonMenName: 'David',
      commonWomenName: 'Sarah',
      propertyUrl: 'https://flagcdn.com/w1280/il.png',
    },
    {
      country: 'Australia',
      commonMenName: 'Jack',
      commonWomenName: 'Olivia',
      propertyUrl: 'https://flagcdn.com/w1280/au.png',
    },
    {
      country: 'New Zealand',
      commonMenName: 'Noah',
      commonWomenName: 'Isla',
      propertyUrl: 'https://flagcdn.com/w1280/nz.png',
    },
    {
      country: 'Nigeria',
      commonMenName: 'Musa',
      commonWomenName: 'Zainab',
      propertyUrl: 'https://flagcdn.com/w1280/ng.png',
    },
    {
      country: 'South Africa',
      commonMenName: 'Sipho',
      commonWomenName: 'Lindiwe',
      propertyUrl: 'https://flagcdn.com/w1280/za.png',
    },
    {
      country: 'Egypt',
      commonMenName: 'Mohamed',
      commonWomenName: 'Mona',
      propertyUrl: 'https://flagcdn.com/w1280/eg.png',
    },
    {
      country: 'Kenya',
      commonMenName: 'John',
      commonWomenName: 'Mary',
      propertyUrl: 'https://flagcdn.com/w1280/ke.png',
    },
    {
      country: 'Ghana',
      commonMenName: 'Emmanuel',
      commonWomenName: 'Esther',
      propertyUrl: 'https://flagcdn.com/w1280/gh.png',
    },
    {
      country: 'Ethiopia',
      commonMenName: 'Tadesse',
      commonWomenName: 'Rahel',
      propertyUrl: 'https://flagcdn.com/w1280/et.png',
    },
    {
      country: 'Tanzania',
      commonMenName: 'Juma',
      commonWomenName: 'Neema',
      propertyUrl: 'https://flagcdn.com/w1280/tz.png',
    },
    {
      country: 'Morocco',
      commonMenName: 'Youssef',
      commonWomenName: 'Amina',
      propertyUrl: 'https://flagcdn.com/w1280/ma.png',
    },
    {
      country: 'Algeria',
      commonMenName: 'Youcef',
      commonWomenName: 'Aicha',
      propertyUrl: 'https://flagcdn.com/w1280/dz.png',
    },
    {
      country: 'Uganda',
      commonMenName: 'John',
      commonWomenName: 'Rose',
      propertyUrl: 'https://flagcdn.com/w1280/ug.png',
    },
    {
      country: 'Cameroon',
      commonMenName: 'Jean',
      commonWomenName: 'Marie',
      propertyUrl: 'https://flagcdn.com/w1280/cm.png',
    },
  ]; 
  click(country:any) { 
    alert(country.country)
  }
}
